### ISSUE TITLE
Please consider new equation for championCdTe.csv

### ISSUE THREAD

**Issue by zunzun** [greysAcademicCode/batch-iv-analysis#1]
For the example data set in championCdTe.csv, I found that the following equation fit extremely well:

y = a * exp(b * exp(c * x)) + Offset

Below is the fitted equation Python code and a  plot of equation vs. raw data from matplotlib.  Please consider adding it to your software.  The standard scipy Levenberg-Marquardt fitter should work fine on other datasets with these coefficients rounded to one or two decimal places as starting values.

import math
def Sigmoidal_GompertzC_Offset_model(x_in):
    a = -1.5025598244123806E+00
    b = -1.4664177224768022E+02
    c = -4.1293894174152364E+00
    Offset = 2.9962806940572947E-02
    temp = a * math.exp(b * math.exp(c*x_in)) + Offset
    return temp

![fit](https://cloud.githubusercontent.com/assets/535821/18975415/754b4b32-8699-11e6-856d-67c6b5787ec6.png)

**Comment by greyltc** [comment]
Hi @zunzun,
Thanks for taking the time to make a suggestion for my project here! That's a pretty good fit. I am working towards refactoring my code so that it's easier for a (advanced) user change the characteristic equation that I'm fitting to, but I'm not there yet.

However, I don't think it's necessarily a good idea to use an equation just because it happens to be a good fit to the data. Most importantly, the the equation we fit to should have physical significance and tell us something we'd like to know about the solar cell (i.e. what the series resistance is). The equation you've chosen there may fit the data alright, but I fail to see any reason to use it beyond the fact that it does a good job of fitting one single case of example data.

**Comment by zunzun** [comment]
I thought it would could be interesting *why* a simple equation fits so well, perhaps this empirically determined model has some as-yet unknown relation to the underlying physics - probably not, but maybe.  The simplicity of the equation itself is suggestive of the possibility.

I have no other data files, if you have time later - and are curious - please send me a few and I can test the fitting on those as well.  I can help with the fitting but not with any possible theoretical underpinnings of the reason for the fit quality, as my backround is in radiation physics and nuclear power.

James, zunzun@zunzun.com
